{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "serviceAccountName" . }}
  labels:
  {{ include "labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

roleRef:
  kind: ClusterRole
  name: {{ include "serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}