apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  {{ if .Values.ingress.host }}type: ClusterIP {{ else }}type: LoadBalancer{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.targetPort }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
